// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = 'https://fpdoikhnobvuigxcfszd.supabase.co'
const SUPABASE_PUBLISHABLE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZwZG9pa2hub2J2dWlneGNmc3pkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg5MjkwNDEsImV4cCI6MjA4NDUwNTA0MX0.mT1CltYf6_V_Cv7rQz1neHzmQaKRFsRveqgxkGAUgds'

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});